Parameters:
  ClusterName:
    Description: The name of the ECS cluster
    Type: String
    Default: tcc-cluster
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: dev
  ApplicationName:
    Description: The name of the application
    Type: String
    Default: banking-accounts

Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        "Fn::ImportValue": !Sub ${ClusterName}-${EnvironmentName}-cluster-name
      DesiredCount: 1
      LaunchType: EC2
      ServiceName: !Sub ${ApplicationName}-${EnvironmentName}
      TaskDefinition:
        "Fn::ImportValue": !Sub ${ApplicationName}-${EnvironmentName}-task-definition
      HealthCheckGracePeriodSeconds: 10
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100

Outputs:
  Service:
      Description: The ARN of the ECS service
      Value: !Ref ECSService
      Export:
        Name: !Sub ${ApplicationName}-${EnvironmentName}-service-arn