Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: dev
  ApplicationName:
    Description: The name of the application
    Type: String
    Default: banking-accounts

Resources:
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ApplicationName}-${EnvironmentName}-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:*
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}

Outputs:
  TaskRole:
    Description: The ARN of the IAM Role to be assumed by the ECS task
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub ${ApplicationName}-${EnvironmentName}-task-role