name: Create feature branch pull request

on:
  push:
    branches:
      - feature/*

permissions:
  pull-requests: write

jobs:
  call-open-pr:
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/create-pr.yml@main