name: Create feature branch pull request

on:
  push:
    branches:
      - feature/*

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Validate if pull request already exists
        id: pull_request_exists
        run: |
          exists=false
          numBranches="$(gh pr list -B ${{ github.event.repository.default_branch }} -H ${{ github.ref_name }} | wc -l)"
          if [ "$numBranches" -gt 0 ]; then
            exists=true
          fi
          echo PR exists: $exists 
          echo 'EXISTS_PULL_REQUEST='$exists >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        if: steps.pull_request_exists.outcome == 'success'
        run: |
          if [ $EXISTS_PULL_REQUEST = false ]; then
            echo Creating pull request
            gh pr create -B ${{ github.event.repository.default_branch }} -H ${{ github.ref_name }} --title 'PR gerado automaticamente. ${{ github.ref_name }} -> ${{ github.event.repository.default_branch }}' --body 'PR gerado automaticamente'
          else
            echo Skipping it because pull request already exists
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
