name: Create feature branch pull request

on:
  push:
    branches:
      - feature/*

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
#      - name: Validate if pull request already exists
#        id: validate_
#        run: gh pr list -B ${{ github.event.repository.default_branch }} -H ${{ github.ref_name }}
      - name: Create pull request
        run: gh pr create -B ${{ github.event.repository.default_branch }} -H ${{ github.ref_name }} --title 'PR gerado automaticamente. ${{ github.ref_name }} -> ${{ github.event.repository.default_branch }}' --body 'PR gerado automaticamente'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
