name: Pull request created to main branch

on:
  pull_request:
    - main

jobs:
  call-maven-build:
    uses: brunovnasci/trunk-based-ci-cd/.github/workflow/maven/build.yml@main
    with:
      java_version: 17