name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          architecture: x64
          cache: maven
      - name: Build application
        run: mvn clean compile

  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          architecture: x64
          cache: maven
      - name: Run application tests
        run: mvn clean test
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: target/site/jacoco/jacoco.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot security analysis
        uses: github/dependabot-action@v2
        with:
          open-pull-requests-limit: 10