name: Pull request created to main branch

on:
  pull_request:
    branches:
      - feature/*

jobs:
  call-maven-build:
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/build.yml@main
    with:
      java_version: 17