name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          architecture: x64
          cache: maven
      - name: Build application
        run: mvn clean install
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/

  coverage-and-quality-gate:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/
      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.7.1
        id: jacoco
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 90
          min-coverage-changed-files: 90
          title: '# :lobster: Coverage Report'
      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Apply quality gate for overall coverage
        if: ${{ steps.jacoco.outputs.coverage-overall < 90.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 90%!')
      - name: Apply quality gate for changed files coverage
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 90.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Changed files coverage is less than 90%!')

  docker-build:
    runs-on: ubuntu-latest
    environment: development
    needs: build-and-test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
          aws-region: us-east-2
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: target/
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - run: echo "${{ steps.login-ecr.outputs.registry }}"
      - name: Build Docker image
        run: docker build -t 140023370685.dkr.ecr.us-east-2.amazonaws.com/banking-accounts:${{ github.sha }} .
      - name: Push docker image
        run: docker push 140023370685.dkr.ecr.us-east-2.amazonaws.com/banking-accounts:${{ github.sha }}

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot security analysis
        uses: github/dependabot-action@v2
        with:
          open-pull-requests-limit: 10