name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          architecture: x64
          cache: maven

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build application
        run: mvn clean compile

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run application tests
        run: mvn clean test

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

  security:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Dependabot security analysis
        uses: github/dependabot-action@v2
        with:
          open-pull-requests-limit: 10