name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  id-token: write
  security-events: write

# TODO: Validar se changelog foi preenchido

jobs:
  build:
    uses: ./.github/actions/build-app
    with:
      java_version: 17

  quality-gate:
    needs: build
    uses: ./.github/workflows/quality-gate.yml

  docker:
    needs: build
    uses: ./.github/workflows/docker-build.yml
    with:
      application_name: banking-accounts
      image_tag: ${{ github.sha }}
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role

  deploy:
    needs: docker
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
      environment: dev
      cluster: tcc-cluster-dev
      docker_image_tag: ${{ needs.docker.outputs.docker-image-tag }}

  security:
    needs: build
    uses: ./.github/workflows/security.yml
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
