name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  id-token: write

# TODO: Validar se changelog foi preenchido

env:
  APPLICATION_NAME: banking-accounts

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      java_version: 17

  quality-gate:
    needs: build-and-test
    uses: ./.github/workflows/quality-gate.yml

  docker-build:
    needs: build-and-test
    uses: ./.github/workflows/docker-build.yml
    with:
      application_name: "$APPLICATION_NAME"
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role

  deploy-to-ecs:
    needs: docker-build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
          aws-region: us-east-2
      - name: echo docker tag
        run: echo "${{ needs.docker-build.outputs.docker-image-tag }}"
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: banking-accounts-dev
          image: ${{ needs.docker-build.outputs.docker-image-tag }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: banking-accounts-dev
          cluster: tcc-cluster-dev
          wait-for-service-stability: true

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot security analysis
        uses: github/dependabot-action@v2
        with:
          open-pull-requests-limit: 10