name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  id-token: write
  security-events: write

jobs:
  build:
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/build.yml@main
    with:
      java_version: 17

  quality-gate:
    needs: build
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/quality-gate.yml@main
    with:
      java_version: 17
      application_name: banking-accounts
      branch_name: ${{ github.head_ref }}
      sonar_host: ${{ vars.SONAR_HOST }}
      sonar_wait_quality_gate: true
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  docker:
    needs: build
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/docker-build.yml@main
    with:
      application_name: banking-accounts
      image_tag: ${{ github.sha }}
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role

#  deploy:
#    needs: docker
#    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/ecs-deploy.yml@main
#    with:
#      application_name: banking-accounts
#      aws_region: us-east-2
#      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
#      environment: dev
#      cluster: tcc-cluster
#      task_definition: .aws/task-definition-dev.json
#      docker_image_tag: ${{ needs.docker.outputs.docker-image-tag }}

  security:
    needs: build
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/security.yml@main
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
