name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  id-token: write

# TODO: Validar se changelog foi preenchido

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      java_version: 17

  quality-gate:
    needs: build-and-test
    uses: ./.github/workflows/quality-gate.yml

  docker-build:
    needs: build-and-test
    uses: ./.github/workflows/docker-build.yml
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role

  deploy-to-ecs:
    needs: docker-build
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
      environment: dev
      cluster: tcc-cluster-dev
      docker_image_tag: ${{ needs.docker-build.outputs.docker-image-tag }}

  security:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Security check"