name: Release application

on:
  release:
    types: [ published ]

permissions:
  id-token: write
  security-events: write

jobs:
  build:
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/build.yml@main
    with:
      java_version: 17

  docker:
    needs: build
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/docker-build.yml@main
    with:
      application_name: banking-accounts
      image_tag: ${{ github.ref_name }}
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role

  deploy-dev:
    needs: docker
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/ecs-deploy.yml@main
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
      environment: dev
      cluster: tcc-cluster
      task_definition: .aws/task-definition-dev.json
      docker_image_tag: ${{ needs.docker.outputs.docker-image-tag }}

  deploy-prod:
    needs: docker
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/ecs-deploy.yml@main
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
      environment: prod
      cluster: tcc-cluster
      task_definition: .aws/task-definition-prod.json
      docker_image_tag: ${{ needs.docker.outputs.docker-image-tag }}

  security:
    needs: build
    uses: brunovnasci/trunk-based-ci-cd/.github/workflows/security.yml@main
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}