name: Start application deployment

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: "Docker image tag"
        required: true
        type: string

permissions:
  id-token: write

jobs:
  get-docker-image:
    uses: ./.github/workflows/get-docker-image.yml
    with:
      application_name: banking-accounts
      image_tag: ${{ inputs.docker_image_tag }}
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role

  deploy-dev:
    needs: get-docker-image
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
      environment: dev
      cluster: tcc-cluster
      task_definition: .aws/task-definition-dev.json
      docker_image_tag: ${{ needs.get-docker-image.outputs.docker-image-tag }}

  deploy-prod:
    needs: get-docker-image
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-github-actions-role
      environment: prod
      cluster: tcc-cluster
      task_definition: .aws/task-definition-prod.json
      docker_image_tag: ${{ needs.get-docker-image.outputs.docker-image-tag }}
