name: Start application deployment

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: "Docker image tag"
        required: true
        type: string

permissions:
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      application_name: banking-accounts
      aws_region: us-east-2
      iam_role: arn:aws:iam::140023370685:role/banking-accounts-dev-github-actions-role
      environment: dev
      cluster: tcc-cluster-dev
      docker_image_tag: ${{ inputs.docker_image_tag }}
